export const targetConfigs = [
  {
    targetIndex: 0,
    title: 'Lugia',
    statusLabel: 'Lugia',
    scale: 0.4,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/lugia.glb'],
    stats: [
      { label: 'Tipo', value: 'Psíquico / Volador' },
      { label: 'HP', value: '106' },
      { label: 'Ataque', value: '90' },
    ],
    skeletonPath: 'Assets/models/Pokemon/lugia.glb',
  },
  {
    targetIndex: 1,
    title: 'Diglett',
    statusLabel: 'Diglett',
    scale: 1,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/diglett.glb'],
    stats: [
      { label: 'Tipo', value: 'Tierra' },
      { label: 'HP', value: '10' },
      { label: 'Ataque', value: '55' },
    ],
    skeletonPath: 'Assets/models/Pokemon/diglett.glb',
  },
  {
    targetIndex: 2,
    title: 'Gengar',
    statusLabel: 'Gengar',
    scale: 0.5,
    rotation: { x:0, y: Math.PI /12, z: 0},
    models: ['Assets/models/Pokemon/gengar.glb'],
    stats: [
      { label: 'Tipo', value: 'Fantasma / Veneno' },
      { label: 'HP', value: '60' },
      { label: 'Ataque', value: '65' },
    ],
    skeletonPath: 'Assets/models/Pokemon/gengar.glb',
  },
  {
    targetIndex: 3,
    title: 'Ho-Oh',
    statusLabel: 'Ho-Oh',
    scale: 0.1,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/ho_oh.glb'],
    stats: [
      { label: 'Tipo', value: 'Fuego / Volador' },
      { label: 'HP', value: '106' },
      { label: 'Ataque', value: '130' },
    ],
    skeletonPath: 'Assets/models/Pokemon/ho-oh.glb',
  },
  {
    targetIndex: 4,
    title: 'Marowak',
    statusLabel: 'Marowak',
    scale: 0.5,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/marowak.glb'],
    stats: [
      { label: 'Tipo', value: 'Tierra' },
      { label: 'HP', value: '60' },
      { label: 'Ataque', value: '80' },
    ],
    skeletonPath: 'Assets/models/Pokemon/marowak.glb',
  },
  {
    targetIndex: 5,
    title: 'Baxcalibur',
    statusLabel: 'Baxcalibur',
    scale: 0.6,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/baxcalibur.glb'],
    stats: [
      { label: 'Tipo', value: 'Dragón / Hielo' },
      { label: 'HP', value: '115' },
      { label: 'Ataque', value: '145' },
    ],
    skeletonPath: 'Assets/models/Pokemon/baxcalibur.glb',
  },
  {
    targetIndex: 6,
    title: 'Graveler',
    statusLabel: 'Graveler',
    scale: 0.5,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/graveler.glb'],
    stats: [
      { label: 'Tipo', value: 'Roca / Tierra' },
      { label: 'HP', value: '55' },
      { label: 'Ataque', value: '95' },
    ],
    skeletonPath: 'Assets/models/Pokemon/graveler.glb',
  },
  {
    targetIndex: 7,
    title: 'Ursaluna',
    statusLabel: 'Ursaluna',
    scale: 0.6,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/ursaluna.glb'],
    stats: [
      { label: 'Tipo', value: 'Tierra / Normal' },
      { label: 'HP', value: '130' },
      { label: 'Ataque', value: '140' },
    ],
    skeletonPath: 'Assets/models/Pokemon/ursaluna.glb',
  },
  {
    targetIndex: 8,
    title: 'Vaporeon',
    statusLabel: 'Vaporeon',
    scale: 0.5,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/vaporeon.glb'],
    stats: [
      { label: 'Tipo', value: 'Agua' },
      { label: 'HP', value: '130' },
      { label: 'Ataque', value: '65' },
    ],
    skeletonPath: 'Assets/models/Pokemon/vaporeon.glb',
  },
  {
    targetIndex: 9,
    title: 'Snorlax',
    statusLabel: 'Snorlax',
    scale: 0.5,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/snorlax.glb'],
    stats: [
      { label: 'Tipo', value: 'Normal' },
      { label: 'HP', value: '160' },
      { label: 'Ataque', value: '110' },
    ],
    skeletonPath: 'Assets/models/Pokemon/snorlax.glb',
  },
  {
    targetIndex: 10,
    title: 'Garchomp',
    statusLabel: 'Garchomp',
    scale: 0.2,
    rotation: { x:0, y: Math.PI / 10, z: 0},
    models: ['Assets/models/Pokemon/garchomp.glb'],
    stats: [
      { label: 'Tipo', value: 'Dragón / Tierra' },
      { label: 'HP', value: '108' },
      { label: 'Ataque', value: '130' },
    ],
    skeletonPath: 'Assets/models/Pokemon/garchomp.glb',
  },
];